name: push action
on: [push]

jobs:                                 # Job 설정
  build:                              # Job ID
    name: hello github action         # Job 이름
    runs-on: ubuntu-18.04             # Job 가상환경 인스턴스
    steps:                            # Steps
      - name: echo Hello1             # Step 이름
        run: echo "Hello step 1"      # Run을 통한 스크립트 실행: Hello setp 1 출력

      - name: echo Hello2             # Step 이름
        run: echo "Hello step 2"      # Run을 통한 스크립트 실행: Hello step 2 출력
