name: push action
on: [push]

jobs:                                 # Job 설정
  echo:                              # Job ID
    name: hello github action         # Job 이름
    runs-on: runner1             # Job 가상환경 인스턴스
    steps:                            # Steps
      - name: echo Hello             # Step 이름
        run: echo "Hello step1"      # Run을 통한 스크립트 실행: Hello setp 1 출력
      - name: output test
        id: abc
        run: echo "::set-output name=abc::danial"
      - name: check abc
        run: echo "${{steps.abc.outputs.abc}}"




# https://help.github.com/en/actions/reference/workflow-commands-for-github-actions