name: Python test
on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: python test
    steps:
    - name: setup python@v2
      uses: actions/setup-python
      with:
        python-version: '3.x'

    - name: run python
      run: |
        python test.py