name: push action
on: [push]

jobs:                                 # Job 설정
  echo:                              # Job ID
    name: echo job         # Job 이름
    # runs-on: self-hosted             # Job 가상환경 인스턴스
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.abc.outputs.abc}}
    steps:                            # Steps
      - name: echo Hello1             # Step 이름
        run: echo "Hello step 1"      # Run을 통한 스크립트 실행: Hello setp 1 출력

      - name: set name abc             # Step 이름
        id: abc
        run: echo "::set-output name=abc::danial"      # 이 스텝에 대한 output 저장

      - name: check abc
        run: echo "${{ steps.abc.outputs.abc }}"
  echo2:
    needs: echo
    name: echo job 2
    runs-on: ubuntu-latest
    steps:
      - name: check abc2
        run: echo "${{ needs.echo.outputs.output1 }}"

# https://help.github.com/en/actions/reference/workflow-commands-for-github-actions
